name: manual build

on:
  workflow_dispatch:
    inputs:
      machine:
        description: "machine to build"
        required: true
        type: choice
        options:
          - all
          - arr
          - backup
          - dashboard
          - fileserver
          - gateway
          - hzc-pango
          - immich
          - llm
          - media
          - monitoring
          - nextcloud
          - oidc
          - paperless
          - reverseproxy
          - simon-desktop
          - vaultwarden

jobs:
  build:
    runs-on: nixos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: build machine configuration
        run: |
          if [ "${{ github.event.inputs.machine }}" = "all" ]; then
            echo "building all machines..."
            nix flake show --json | \
              jq -r '.nixosConfigurations | keys[]' | \
              while read machine; do
                echo "building $machine..."
                nix build ".#nixosConfigurations.$machine.config.system.build.toplevel" --print-build-logs
              done
          else
            echo "building ${{ github.event.inputs.machine }}..."
            nix build ".#nixosConfigurations.${{ github.event.inputs.machine }}.config.system.build.toplevel" --print-build-logs
          fi

      - name: show build results
        run: |
          ls -lah result*
