name: semantic release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: nixos-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: setup node for semantic-release
        run: |
          nix profile install nixpkgs#nodejs_22

      - name: install semantic-release dependencies
        run: |
          npm install -g \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits

      - name: run semantic-release
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          GIT_AUTHOR_NAME: forgejo-actions[bot]
          GIT_AUTHOR_EMAIL: forgejo-actions[bot]@users.noreply.codeberg.org
          GIT_COMMITTER_NAME: forgejo-actions[bot]
          GIT_COMMITTER_EMAIL: forgejo-actions[bot]@users.noreply.codeberg.org
        run: |
          # configure git to allow pushing
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"

          # run semantic-release with codeberg config
          npx semantic-release --extends .releaserc.codeberg.yml
