{
  config,
  pkgs,
  lib,
  ...
}:
{
  boot = {
    growPartition = true;

    tmp.cleanOnBoot = true;

    loader = {
      timeout = lib.mkDefault 0;
      generationsDir.copyKernels = true;
      efi.canTouchEfiVariables = true;

      systemd-boot = {
        enable = true;
        configurationLimit = 5;
        consoleMode = lib.mkDefault "max";
        editor = false;
      };
    };

    supportedFilesystems = [
      "btrfs"
    ];

    initrd = {
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;
      systemd = {
        enable = true;
        strip = true;
        suppressedUnits = lib.mkIf config.systemd.enableEmergencyMode [
          "emergency.service"
          "emergency.target"
        ];
      };
    };
    kernelPackages = pkgs.linuxPackages_latest; # pkgs.linuxPackages_xanmod_latest, pkgs.linuxPackages_zen, pkgs.linuxPackages_lqx, linuxPackages_latest

    kernelParams = [
      # https://en.wikipedia.org/wiki/Kernel_page-table_isolation
      # auto means kernel will automatically decide the pti state
      "pti=auto" # on | off

      # CPU idle behaviour
      #  poll: slightly improve performance at cost of a hotter system (not recommended)
      #  halt: halt is forced to be used for CPU idle
      #  nomwait: Disable mwait for CPU C-states
      "idle=nomwait" # poll | halt | nomwait

      # disable displaying of the built-in Linux logo
      "logo.nologo"

      # disable usb autosuspend
      "usbcore.autosuspend=-1"

      "nohibernate"
    ];
  };
}
