{
  pkgs,
  lib,
  ...
}:
{
  boot = {
    # This pulls in nixos-containers which depends on Perl.
    enableContainers = false;

    growPartition = true;

    tmp.cleanOnBoot = true;

    loader = {
      timeout = lib.mkDefault 0;
      generationsDir.copyKernels = true;

      systemd-boot = {
        enable = false;
      };

      grub = {
        enable = true;
        # Being headless, we don't need a GRUB splash image.
        splashImage = null;
      };
    };

    supportedFilesystems = [
      "ext4"
      "xfs"
    ];

    initrd = {
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;
    };

    kernelPackages = pkgs.linuxPackages_latest; # pkgs.linuxPackages_xanmod_latest, pkgs.linuxPackages_zen, pkgs.linuxPackages_lqx, linuxPackages_latest

    kernelModules = [
      "dm_crypt" # Disk encryption support (used in Longhorn)
      "vfio_pci" # PCI passthrough (needed for NVMe or virtualization)
      "uio_pci_generic" # Generic PCI driver (may be needed)
      "nvme_tcp" # NVMe over TCP (storage-related)
    ];

    kernelParams = [

      # Since we can't manually respond to a panic, just reboot.
      "panic=1"
      "boot.panic_on_fail"
      "vga=0x317"

      # https://en.wikipedia.org/wiki/Kernel_page-table_isolation
      # auto means kernel will automatically decide the pti state
      "pti=auto" # on | off

      # CPU idle behaviour
      #  poll: slightly improve performance at cost of a hotter system (not recommended)
      #  halt: halt is forced to be used for CPU idle
      #  nomwait: Disable mwait for CPU C-states
      "idle=nomwait" # poll | halt | nomwait

      # disable displaying of the built-in Linux logo
      "logo.nologo"

      "nohibernate"
    ];
  };
}
