{
  imports = [
    ./emulators/alacritty.nix
    ./emulators/wezterm.nix
    ./emulators/kitty.nix
    ./programs/bat.nix
    ./programs/btop.nix
    ./programs/cli.nix
    ./programs/fzf.nix
    ./programs/git.nix
    ./programs/tmux.nix
    ./programs/direnv.nix
    ./programs/dircolors.nix
    ./programs/yazi
    ./shell/starship.nix
    ./shell/bash.nix
    ./shell/zsh
  ];
}
