{ pkgs, lib, ... }:
{
  boot = {
    swraid.enable = lib.mkDefault false;
    loader = {
      timeout = lib.mkDefault 2;
      generationsDir.copyKernels = true;
      efi.canTouchEfiVariables = true;
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
        consoleMode = lib.mkDefault "max";
        editor = false;
      };
    };

    tmp = {
      # /tmp on tmpfs, lets it live on your ram
      # it defaults to FALSE, which means you will use disk space instead of ram
      # enable tmpfs tmp on anything except servers and builders
      useTmpfs = true;

      # If not using tmpfs, which is naturally purged on reboot, we must clean
      # /tmp ourselves. /tmp should be volatile storage!
      cleanOnBoot = true;

      # The size of the tmpfs, in percentage form
      # this defaults to 50% of your ram, which is a good default
      # but should be tweaked based on your systems capabilities
      tmpfsSize = "50%";
    };

    initrd = {
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;
      systemd = {
        # enable systemd in initrd
        enable = true;
        strip = true;
      };
    };
    kernelPackages = pkgs.linuxPackages_xanmod_latest; # pkgs.linuxPackages_xanmod_latest, pkgs.linuxPackages_zen, pkgs.linuxPackages_lqx, linuxPackages_latest
    kernelParams = [
      # https://en.wikipedia.org/wiki/Kernel_page-table_isolation
      # auto means kernel will automatically decide the pti state
      "pti=auto" # on | off

      # CPU idle behaviour
      #  poll: slightly improve performance at cost of a hotter system (not recommended)
      #  halt: halt is forced to be used for CPU idle
      #  nomwait: Disable mwait for CPU C-states
      "idle=nomwait" # poll | halt | nomwait

      # disable usb autosuspend
      "usbcore.autosuspend=-1"

      # disable displaying of the built-in Linux logo
      "logo.nologo"

      # disable watchdog timer
      "nowatchdog"
      "modprobe.blacklist=sp5100_tco"
    ];
  };
}
