{
  config,
  pkgs,
  lib,
  ...
}:
{

  boot = {
    # This pulls in nixos-containers which depends on Perl.
    enableContainers = false;

    growPartition = true;

    tmp.cleanOnBoot = lib.mkDefault true;

    #zfs.enabled = true;

    loader = {
      timeout = lib.mkDefault 0;
      generationsDir.copyKernels = true;

      systemd-boot = {
        enable = false;
        configurationLimit = lib.mkDefault 5;
      };

      grub = {
        enable = true;
        configurationLimit = lib.mkDefault 5;
        efiSupport = true;
        efiInstallAsRemovable = true;
        # Being headless, we don't need a GRUB splash image.
        splashImage = null;
        memtest86.enable = lib.mkForce false;
      };
    };

    # Make the installer more likely to succeed in low memory
    # environments.  The kernel's overcommit heustistics bite us
    # fairly often, preventing processes such as nix-worker or
    # download-using-manifests.pl from forking even if there is
    # plenty of free memory.
    kernel.sysctl."vm.overcommit_memory" = "1";
    swraid = {
      enable = true;
      # remove warning about unset mail
      mdadmConf = "PROGRAM ${pkgs.coreutils}/bin/true";
    };

    supportedFilesystems = [
      "ext4"
      "xfs"
      "btrfs"
      "zfs"
    ];

    initrd = {
      network.udhcpc.enable = lib.mkIf (!config.boot.initrd.systemd.enable) true;
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;

      systemd.suppressedUnits = lib.mkIf config.systemd.enableEmergencyMode [
        "emergency.service"
        "emergency.target"
      ];
    };

    kernelModules = [
      "dm_crypt" # Disk encryption support (used in Longhorn)
      "vfio_pci" # PCI passthrough (needed for NVMe or virtualization)
      "uio_pci_generic" # Generic PCI driver (may be needed)
      "nvme_tcp" # NVMe over TCP (storage-related)
    ];

    kernelParams = [

      # Since we can't manually respond to a panic, just reboot.
      "panic=1"
      "boot.panic_on_fail"
      "vga=0x317"

      # https://en.wikipedia.org/wiki/Kernel_page-table_isolation
      # auto means kernel will automatically decide the pti state
      "pti=auto" # on | off

      # CPU idle behaviour
      #  poll: slightly improve performance at cost of a hotter system (not recommended)
      #  halt: halt is forced to be used for CPU idle
      #  nomwait: Disable mwait for CPU C-states
      "idle=nomwait" # poll | halt | nomwait

      # disable displaying of the built-in Linux logo
      "logo.nologo"

      "nohibernate"
    ];
  };
}
